# Generated by Django 4.2.7 on 2024-05-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='author',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='audio',
            name='title',
            field=models.CharField(db_index=True, max_length=35),
        ),
    ]
