# Generated by Django 4.2.7 on 2024-06-05 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_comments_comment_post_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='answers',
        ),
        migrations.AlterField(
            model_name='answer',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='posts.comment'),
        ),
    ]
