# Generated by Django 4.2.7 on 2024-04-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userprofile_friends_remove_userprofile_photos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(blank=True, default='static/images/User-avatar.svg.png', null=True, upload_to='users_avatars'),
        ),
    ]
