# Generated by Django 4.2.7 on 2024-05-01 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_users_friends_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
