# Generated by Django 4.2.7 on 2024-05-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='privacy',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=3),
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
