# Generated by Django 4.2.7 on 2024-05-01 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_users_privacy_delete_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='privacy',
        ),
    ]
