# Generated by Django 4.2.7 on 2024-05-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='is_online',
            field=models.BooleanField(default=None),
        ),
    ]
