version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      uvicorn application.asgi:application --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1

volumes:
  static_volume: