version: '3.8'
x-environment-defaults: &environment-defaults
  DB_NAME: social_network
  DB_USER: postgres
  DB_PASSWORD: wicki
  DB_HOST: db
  DB_PORT: 5432
  REDIS_SERVER: redis://redis:6379/0
  REDIS_HOST: redis
  REDIS_PORT: 6379 
services:
  web:
    build:
      context: .
    # command: /app/entrypoint.sh
    container_name: web
    environment:
      <<: *environment-defaults
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
  redis:
    image: redis:latest
    container_name: redis
    environment:
      <<: *environment-defaults
    ports:
      - "6379:6379"
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: social_network
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wicki
    ports:
      - "5433:5432"
    # environment:
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: wicki
    #   POSTGRES_DB: social_network
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
      - static_volume:/app/static
    depends_on:
      - web

volumes:
  pgdata:
  static_volume:
  media_volume: