version: '3.8'

services:
  web:
    build: .
    command: uvicorn application.asgi:application --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1

volumes:
  static_volume: