# Generated by Django 4.2.7 on 2024-05-01 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPhoto',
        ),
    ]
